# Generated by Django 3.0.5 on 2021-01-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoleApp', '0002_auto_20210119_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='is_tch',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='update',
            name='image',
            field=models.ImageField(default='profile.png', upload_to='profile_pics/'),
        ),
    ]
