# Generated by Django 2.2.14 on 2020-12-16 07:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Others', 'Others')], max_length=10, null=True)),
                ('branch', models.CharField(choices=[('None', 'None'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('MEC', 'MEC'), ('EEE', 'EEE'), ('IT', 'IT')], max_length=4, null=True)),
                ('lang', multiselectfield.db.fields.MultiSelectField(choices=[('Telugu', 'Telugu'), ('Hindi', 'Hindi'), ('English', 'English'), ('Malayalam', 'Malayalam')], max_length=30, null=True)),
            ],
        ),
    ]
