# Generated by Django 2.2.14 on 2020-12-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormsApp', '0004_auto_20201216_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='branch',
            field=models.CharField(choices=[('None', 'None'), ('ECE', 'ECE'), ('MEC', 'MEC'), ('CSE', 'CSE'), ('IT', 'IT')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='lang',
            field=models.CharField(choices=[('Telugu', 'Telugu'), ('Hindi', 'Hindi'), ('English', 'English'), ('Malayalam', 'Malayalam')], max_length=10, null=True),
        ),
    ]
