# Generated by Django 2.2.14 on 2020-12-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormsApp', '0005_auto_20201216_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='branch',
            field=models.CharField(choices=[('Select', 'Select'), ('ECE', 'ECE'), ('MEC', 'MEC'), ('CSE', 'CSE'), ('IT', 'IT')], default=None, max_length=10, null=True),
        ),
    ]
