# Generated by Django 2.2.14 on 2020-12-21 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormsApp', '0006_auto_20201216_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='lang',
        ),
    ]
