# Generated by Django 3.0.6 on 2020-12-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('dec', models.DecimalField(decimal_places=2, max_digits=5)),
                ('email', models.EmailField(max_length=30)),
                ('upload', models.FileField(upload_to='path/')),
                ('flt', models.FloatField()),
                ('img', models.ImageField(upload_to=None)),
                ('age', models.IntegerField()),
                ('txt', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
