# Generated by Django 3.0.6 on 2020-12-11 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0003_student_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile',
        ),
    ]
