# Generated by Django 3.0.6 on 2020-12-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0005_auto_20201211_1740'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employe',
            new_name='Employee',
        ),
    ]
