# Generated by Django 2.2.14 on 2020-12-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0008_auto_20201212_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField(max_length=30)),
                ('stunum', models.IntegerField()),
                ('branch', models.CharField(choices=[('CSE', 'cse'), ('ECE', 'ece'), ('MEC', 'mec'), ('EEE', 'eee'), ('IT', 'it')], max_length=4)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
    ]
