# Generated by Django 2.2.14 on 2020-12-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0009_studentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='lang',
            field=models.CharField(choices=[('Telugu', 'Telugu'), ('Hindi', 'Hindi'), ('English', 'English')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('MEC', 'MEC'), ('EEE', 'EEE'), ('IT', 'IT')], max_length=4, null=True),
        ),
    ]
