# Generated by Django 2.2.14 on 2020-12-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0010_auto_20201214_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='stunum',
            field=models.IntegerField(null=True),
        ),
    ]
