# Generated by Django 2.2.14 on 2020-12-14 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0011_auto_20201214_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='lang',
        ),
    ]
