# Generated by Django 2.2.14 on 2020-12-14 07:40

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0013_studentdetails_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='gender',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='branch',
            field=models.CharField(choices=[('None', 'None'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('MEC', 'MEC'), ('EEE', 'EEE'), ('IT', 'IT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='lang',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Telugu', 'Telugu'), ('Hindi', 'Hindi'), ('English', 'English')], max_length=20, null=True),
        ),
    ]
