# Generated by Django 2.2.14 on 2020-12-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0014_auto_20201214_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='lang',
            field=models.CharField(choices=[('Telugu', 'Telugu'), ('Hindi', 'Hindi'), ('English', 'English')], max_length=30, null=True),
        ),
    ]
