# Generated by Django 2.2.14 on 2020-12-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0016_auto_20201214_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Others', 'Others')], max_length=10, null=True),
        ),
    ]
