# Generated by Django 2.2.14 on 2020-12-15 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0017_auto_20201214_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='DOB',
        ),
    ]
